apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:15.0
          ports:
            - containerPort: 5432
          env:  
          - name: POSTGRES_USER
            value: "newsuser"
          - name: POSTGRES_PASSWORD
            value: "newspwd"
          - name: POSTGRES_DB
            value: "news"
---
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:   
  selector:
    app: postgre
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: fabricioveronez/devops4devs-news:v3
          ports:
            - containerPort: 8080
          env: 
            - name: DB_DATABASE
              value: "news"
            - name: DB_USERNAME
              value: "newsuser"
            - name: DB_PASSWORD
              value: "newspwd"
            - name: DB_HOST
              value: postgre
            - name: AWS_ACCESS_KEY
              value: {{AWS_ACCESS_KEY}}
            - name: AWS_ACCESS_SECRET
              value: {{AWS_ACCESS_SECRET}}
            - name: AWS_S3_BUCKET_NAME
              value: devops4devs-files
            - name: STORAGE_TYPE
              value: S3
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:   
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer